<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>services score</name>
  <uuid>fbc0ed23-bee0-4a55-91a3-97d4036559d1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the number of elements in the Services requested of Services is more than 3		
then
	add 1 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
