<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>set industry input</name>
  <uuid>989d08eb-b6c9-4fc9-b6eb-8ecf3837c0fe</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the clientindustry is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
